CREATE TABLE IF NOT EXISTS CONFIG_SMARTBAND (
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
MAC_ADDRESS VARCHAR(17) NOT NULL,
NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONFIG_CORE (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    PHONE_NUMBER NUMBER(13) NOT NULL,
    TIME_BETWEEN_CONSULTS NUMBER(3) NOT NULL
);